#%RAML 1.0 DataType
displayName: Create Customer Response
type: object
properties:
  customerId:
    type: string
    required: true
    example: "4d4de7d6-7f5e-4778-9c70-babba6c25c55"
  success: 
    type: boolean
    required: true
    example: true
  message:
    type: string
    required: true
    example: "Customer Created Successfully"