#%RAML 1.0 DataType
displayName: Create Customer Request
type: object
properties:
  personalInformation:
    type: object
    required: false
    properties:
      firstName:
        type: string
        required: false
        example: "Ulrich"
      lastName: 
        type: string
        required: false
        example: "Nielsen"
      companyName:
        type: string
        required: false
        example: "E-ffoc"
      email:
        type: string
        required: false
        example: "ulrichN@effoc.com"
      phone:
        type: string
        required: false
        example: "+494341927420"
  address:
    type: array
    required: false
    items:
      type: object
      properties:
        street:
          type: string
          required: false
          example: "Steinbrueckstrasse"
        houseNumber: 
          type: number
          required: false
          example: 114
        city:
          type: string
          required: false
          example: "Nuremberg"
        country:
          type: string
          required: false
          example: "Germany"
        postalCode:
          type: string
          required: false
          example: "90408"